name: finanstic_website
description: Manage your expenses like never before.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: 2.2.0
  provider: ^6.0.5
  video_player: ^2.6.1
  url_launcher: ^6.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  image_path: "assets/finanstic_app_icon.png"
  android: true
  ios: false
